<?xml version="1.0" encoding="utf-8"?><Database Name="QLNhanSu" Class="QLNhanSuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=QLNhanSu;Integrated Security=True" SettingsObjectName="Employee_Management.Properties.Settings" SettingsPropertyName="QLNhanSuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNgayCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NghiCoPhep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NghiKhongPhep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LamThem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_ChamCong" Member="NhanVien" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViPham" Member="ViPhams">
    <Type Name="ViPham">
      <Column Name="MaViPham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayKyLuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MucDoViPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_ViPham" Member="NhanVien" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaChucVu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChucVu_NhanVien" Member="NhanViens" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.DanToc" Member="DanTocs">
    <Type Name="DanToc">
      <Column Name="MaDanToc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanToc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DanToc_NhanVien" Member="NhanViens" ThisKey="MaDanToc" OtherKey="MaDanToc" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.KhenThuong" Member="KhenThuongs">
    <Type Name="KhenThuong">
      <Column Name="MaKhenThuong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayKhenThuong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MucDoKhenThuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_KhenThuong" Member="NhanVien" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Luong" Member="Luongs">
    <Type Name="Luong">
      <Column Name="MaSoLuong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LuongCoBan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HeSoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TienThuong" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TienPhat" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Luong_NhanVien" Member="NhanViens" ThisKey="MaSoLuong" OtherKey="MaSoLuong" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="IdNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaDanToc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTonGiao" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChucVu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_ChamCong" Member="ChamCongs" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="ChamCong" />
      <Association Name="NhanVien_ViPham" Member="ViPhams" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="ViPham" />
      <Association Name="NhanVien_KhenThuong" Member="KhenThuongs" ThisKey="IdNhanVien" OtherKey="IdNhanVien" Type="KhenThuong" />
      <Association Name="ChucVu_NhanVien" Member="ChucVu" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="ChucVu" IsForeignKey="true" />
      <Association Name="DanToc_NhanVien" Member="DanToc" ThisKey="MaDanToc" OtherKey="MaDanToc" Type="DanToc" IsForeignKey="true" />
      <Association Name="Luong_NhanVien" Member="Luong" ThisKey="MaSoLuong" OtherKey="MaSoLuong" Type="Luong" IsForeignKey="true" />
      <Association Name="TonGiao_NhanVien" Member="TonGiao" ThisKey="MaTonGiao" OtherKey="MaTonGiao" Type="TonGiao" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="IdTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TonGiao" Member="TonGiaos">
    <Type Name="TonGiao">
      <Column Name="MaTonGiao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTonGiao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TonGiao_NhanVien" Member="NhanViens" ThisKey="MaTonGiao" OtherKey="MaTonGiao" Type="NhanVien" />
    </Type>
  </Table>
</Database>